name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/amd64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
            --platform ${{ matrix.platform }} \
            -t ${{ secrets.DOCKER_USERNAME }}/jenkins:latest \
            ./jenkins/

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/jenkins:latest
