name: Build and push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64/v8]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build create --use
          docker build build \
            --platform ${{ matrix.platform }} \
            -t ${{ secrets.DOCKER_USERNAME }}/jenkins:latest ./jenkins/
          docker push ${{ secrets.DOCKER_USERNAME }}/jenkins:latest
